### PR TITLE
Allowing the resolveReferenceTypesAsNullable option to be set 

### PR DESCRIPTION
**Pull request by promontis**
... from the  ProducerBuilderExtensions

### CODE REVIEW

**Comment by promontis** [comment]
#17 said I should set the `resolveReferenceTypesAsNullable` property to `true` to generate unions for reference types. However, this property is not available in the ProducerBuilderExtensions. 

This PR adds that.

**Comment by promontis** [comment]
@dstelljes can you review?

**Comment by promontis** [comment]
@dstelljes where can I provide a `ITypeResolver`, because that is exactly what I need :)
I couldn't it on `ProducerBuilderExtensions`. Should I pass it via `SchemaRegistrySerializerBuilder` and  add a new `SchemaBuilder` with the typeResolver? 

Let me try it

**Comment by promontis** [comment]
ah yes... this seems to work:

`new SchemaRegistrySerializerBuilder(registry, new SchemaBuilder(null, new DataContractResolver(resolveReferenceTypesAsNullable: true)))`

It was a bit hidden :) 

Closing this now

**Comment by dstelljes** [comment]
Yeah, sorry, I could have been more clear. We should also document this kind of thing better, opened #23 to track.

**Comment by promontis** [comment]
@dstelljes no problem... I should've looked better :) But I agree this could be documented better ;)

Could you have a look at #17? I've added a comment :)

**Pull request closed without merging**
