### PR TITLE
String is by default nullable in .NET

### PR DESCRIPTION
**Pull request by promontis**
String is by default nullable in .NET

### CODE REVIEW

**Comment by promontis** [comment]
Hi @dstelljes !

Thanks for this library! I've marked string to be nullable, because in .NET this is the case

**Comment by dstelljes** [comment]
Hey @promontis, thanks for the PR!

The reflection resolver cases intentionally don’t resolve reference types as nullable. That’s to enable the `resolveReferenceTypesAsNullable` option on the resolver itself, which defaults to false because we find it preferable not to have a bunch of unions in generated schemas.

If you set that option to true (in code or using the `--nullable-references` flag on `dotnet avro create`), you’ll get `["null", ...]` unions for all reference types.

There are a couple alternative options we’d entertain:

1. In a future major release, resolve all reference types as nullable by default.

2. Allow developers to explicitly specify which reference types should and should not be nullable (probably via attributes).

**Comment by promontis** [comment]
Ah awesome! I thought it needed to set the `nullable` to `true` in the codebase, but I can specify it myself! Awesome!

I'll close this PR.

**Comment by promontis** [comment]
@dstelljes having passed `resolveReferenceTypesAsNullable: true` I still get the error for a string not being null.

Thinking about it, this PR was making `string` nullable. `string` is not a reference type, but a value type which can be also null, but not nullable (really inconsistent if you'd ask me, Microsoft).

AFAIK `resolveReferenceTypesAsNullable: true` doesn't result into a nullable union for strings. 
I'm wondering what you think would be best in this scenario, as I think string should be made nullable, because it is defined like that by .NET.

**Comment by dstelljes** [comment]
`resolveReferenceTypesAsNullable: true` should produce `["null","string"]`:

```shell
$ dotnet avro create -t System.String --nullable-references
["null","string"]
```

Strings [are reference types](https://stackoverflow.com/questions/636932/in-c-why-is-string-a-reference-type-that-behaves-like-a-value-type), so I think the behavior is correct. It gets a little weirder with the nullable reference type feature landing in C# 8, since that’s entirely a compiler thing (nullable value types are `Nullable<T>`; nullable reference types are not).

**Comment by promontis** [comment]
Mmm... I think you are correct. I'll check tomorrow when I'm back at my desk why it is not working in my  code! Thanks for helping so far

**Comment by promontis** [comment]
@dstelljes yes it works! 🎉 

I had to remove the schema and let it upgrade it

**Pull request closed without merging**
