### PR TITLE
Added DependentProducerBuilderExtensions

### PR DESCRIPTION
**Pull request by promontis**

### CODE REVIEW

**Comment by promontis** [comment]
Hi @dstelljes! 

From #32 I've added this class as the DependentProducerBuilder (https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/DependentProducerBuilder.cs) from Kafka does not inherit from ProducerBuilder, thus you are missing these extensions.

**Comment by dstelljes** [comment]
These extensions were added with https://github.com/ch-robinson/dotnet-avro/pull/33 (merged into the 3.x release branch, planning to cut that by the end of the month). Thanks for doing the work—sorry it wasn’t more obvious that it had already been completed.

**Comment by promontis** [comment]
Ah awesome! So the Nuget 3.0.0-rc.0 should already have these?

**Comment by dstelljes** [comment]
Just cut 3.0.0-rc.1, should be available in NuGet shortly.

**Pull request closed without merging**
